from enum import Enum


class Status(Enum):
    newborn = "newborn"
    not_newborn = "-newborn"
    kitten = "kitten"
    not_kitten = "-kitten"
    apprentice = "apprentice"
    not_apprentice = "-apprentice"
    mediator_apprentice = "mediator apprentice"
    not_mediator_apprentice = "-mediator apprentice"
    medicine_cat_apprentice = "healer apprentice"
    not_medicine_cat_apprentice = "-healer apprentice"
    warrior = "warrior"
    not_warrior = "-warrior"
    mediator = "mediator"
    not_mediator = "-mediator"
    medicine_cat = "healer"
    not_medicine_cat = "-healer"
    deputy = "deputy"
    not_deputy = "-deputy"
    leader = "leader"
    not_leader = "-leader"
    elder = "elder"
    not_elder = "-elder"
    any = "any"
    living = "living"
    starclan = "starclan"
    darkforest = "darkforest"
    unknownresidence = "unknownresidence"
    kittypet = "kittypet"
    loner = "loner"
    rogue = "rogue"
    former_Clancat = "former Clancat"
    exiled = "exiled"
    lost = "lost"
    not_lost = "-lost"
    outside_cat = "outside cat"
    clancat = "clancat"
